//
//  TesteViewController.swift
//  PokedexKanto
//
//  Created by Raul de Medeiros on 31/01/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TesteDisplayLogic: class
{
  func displaySomething(viewModel: Teste.Something.ViewModel)
}

class TesteViewController: UIViewController, TesteDisplayLogic
{
  var interactor: TesteBusinessLogic?
  var router: (NSObjectProtocol & TesteRoutingLogic & TesteDataPassing)?

  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = TesteInteractor()
    let presenter = TestePresenter()
    let router = TesteRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = Teste.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Teste.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
